[package]
name = "avl"
version = "0.2.0"
authors = ["Oliver Anhuth <oliver.anhuth@zoho.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
consistency_check = []

[dependencies]

[dev-dependencies]
rand = "0.7.3"
